use sun2000 defaults, remove kW unit and only use W
olivergregorius/sun2000_modbus pull request #18
Opened 2023-01-11 20:40 UTC by daniel309

2023-01-11 21:07 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    MaximumPowerOfChargeFromGrid = Register(47244, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RW, None)
Similar to https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067455325
Gain must be adjusted to be 0.1, data type and all values must be changed accordingly.

2023-01-11 21:09 UTC, olivergregorius requested changes
Thanks for your contribution!

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    ForcibleDischargePower = Register(47249, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RW, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    MaximumChargeFromGridPower = Register(47590, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RW, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit1BatteryPack1ChargeDischargePower = Register(38233, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit1BatteryPack2ChargeDischargePower = Register(38275, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit1BatteryPack3ChargeDischargeStatus = Register(38317, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit2BatteryPack1ChargeDischargePower = Register(38359, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit2BatteryPack2ChargeDischargePower = Register(38401, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-11 21:09 UTC, olivergregorius commented on sun2000_modbus/registers.py
> +    Unit2BatteryPack3ChargeDischargePower = Register(38443, 2, datatypes.DataType.INT32_BE, 1, "W", AccessType.RO, None)
See https://github.com/olivergregorius/sun2000_modbus/pull/18/files#r1067457689

2023-01-13 21:02 UTC, daniel309 commented on sun2000_modbus/inverter.py
> +    def __init__(self, host, port=502, timeout=5, wait=2, unit=1):
interesting. I did google around a bit and it seems to vary by model. let me put a comment and revert back to 0

2023-01-13 21:09 UTC, daniel309 commented
Thanks, my intention was to standardize all registers that report power and dont have a unit in their name in W. Current master has a mix (e.g. Inverter InputPower and ActivePower are kW, vs. Battery ChargeDischargePower and Meter ActivePower are W already). I found this quite annoying and that caused me to start this PR. 

Btw. I messed up the PR. Wanted to merge into my fork's master and only later open a PR for upstream master.

Let me fix my stuff and then get back. I also wanted to change some of the isConnected logic and add an option to always close the tcp connection. My inverter is very sensitive to leaving the tcp connection open, others reported similar problems

https://www.elektroda.com/rtvforum/topic3828425-30.html

https://skyboo.net/2022/02/huawei-sun2000-why-using-a-usb-dongle-for-monitoring-is-not-a-good-idea/

let me fix all that in my fork, fix tests and then open a PR for when I am done. Will get back. Closing this PR for now.

2023-01-13 21:09 UTC, closed without merging